services:
  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
      image: camunda/zeebe:${CAMUNDA_PLATFORM_VERSION:-8.2.0-alpha5}
      container_name: zeebe
      ports:
        - "26500:26500"
        - "9600:9600"
      environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/environment-variables/
        - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
        - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
        - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
        # allow running with low disk space
        - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
        - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
        - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
      restart: always
      volumes:
        - zeebe:/usr/local/zeebe/data


volumes:
  zeebe: